"""initial schema

Revision ID: 74599f39582e
Revises: 
Create Date: 2026-09-23 14:18:09.225975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74599f39582e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('permission_scope', sa.Enum('full_plan', 'position_group', 'situational', 'video_only', name='permissionscope'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('category', sa.Enum('situation', 'down_distance', 'field_zone', 'priority', 'personnel_note', name='tagcategory'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_plans',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('opponent_name', sa.String(length=255), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planning', 'practice', 'finalized', 'played', 'archived', name='gameplanstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnel_groups',
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('rb_count', sa.Integer(), nullable=False),
    sa.Column('te_count', sa.Integer(), nullable=False),
    sa.Column('wr_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_members_email'), 'staff_members', ['email'], unique=True)
    op.create_table('formations',
    sa.Column('personnel_group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('side_of_ball', sa.Enum('offense', 'defense', 'special_teams', name='sideofball'), nullable=False),
    sa.Column('diagram_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_group_id'], ['personnel_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_records',
    sa.Column('game_plan_id', sa.Uuid(), nullable=False),
    sa.Column('pushed_entity_type', sa.Enum('sideline_sheet', 'practice_script', 'scout_card', name='pushedentitytype'), nullable=False),
    sa.Column('pushed_entity_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pushed_by_staff_member_id', sa.Uuid(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_audience', sa.Enum('full_team', 'offense', 'defense', 'special_teams', 'position_group', name='targetaudience'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_plan_id'], ['game_plans.id'], ),
    sa.ForeignKeyConstraint(['pushed_by_staff_member_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_assignments',
    sa.Column('game_plan_id', sa.Uuid(), nullable=False),
    sa.Column('staff_member_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_plan_id'], ['game_plans.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scout_cards',
    sa.Column('game_plan_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('generation_mode', sa.Enum('manual_assist', 'auto_from_tendencies', name='scoutcardgenerationmode'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_plan_id'], ['game_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sideline_sheets',
    sa.Column('game_plan_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_plan_id'], ['game_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_tasks',
    sa.Column('game_plan_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_staff_member_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('cycle_day', sa.Enum('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='cycleday'), nullable=False),
    sa.Column('cycle_phase', sa.Enum('self_scout', 'install', 'practice_script', 'final_prep', 'game', name='cyclephase'), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'blocked', 'done', name='taskstatus'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_entity_type', sa.String(length=50), nullable=True),
    sa.Column('linked_entity_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_member_id'], ['staff_members.id'], ),
    sa.ForeignKeyConstraint(['game_plan_id'], ['game_plans.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_ack_receipts',
    sa.Column('push_record_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['push_record_id'], ['push_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plays',
    sa.Column('formation_id', sa.Uuid(), nullable=False),
    sa.Column('game_plan_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('play_type', sa.Enum('run', 'pass_', 'rpo', 'screen', 'special_teams', name='playtype'), nullable=False),
    sa.Column('call_sheet_text', sa.String(length=500), nullable=False),
    sa.Column('diagram_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['game_plan_id'], ['game_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_scripts',
    sa.Column('game_plan_id', sa.Uuid(), nullable=False),
    sa.Column('practice_date', sa.Date(), nullable=False),
    sa.Column('generated_from_sideline_sheet_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='scriptstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_plan_id'], ['game_plans.id'], ),
    sa.ForeignKeyConstraint(['generated_from_sideline_sheet_id'], ['sideline_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_clips',
    sa.Column('game_plan_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('upload', 'external_url', name='clipsource'), nullable=False),
    sa.Column('storage_url', sa.String(length=2000), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('formation_id', sa.Uuid(), nullable=True),
    sa.Column('opponent_context', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['game_plan_id'], ['game_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip_annotations',
    sa.Column('clip_id', sa.Uuid(), nullable=False),
    sa.Column('author_staff_member_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('note_text', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_staff_member_id'], ['staff_members.id'], ),
    sa.ForeignKeyConstraint(['clip_id'], ['video_clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip_play_links',
    sa.Column('clip_id', sa.Uuid(), nullable=False),
    sa.Column('play_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['video_clips.id'], ),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip_tags',
    sa.Column('clip_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['video_clips.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('play_tags',
    sa.Column('play_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scout_card_entries',
    sa.Column('scout_card_id', sa.Uuid(), nullable=False),
    sa.Column('opponent_play_label', sa.String(length=255), nullable=False),
    sa.Column('formation_id', sa.Uuid(), nullable=True),
    sa.Column('down_distance_bucket', sa.Enum('first_10', 'second_short', 'second_medium', 'second_long', 'third_short', 'third_medium', 'third_long', 'fourth_down', 'red_zone', 'goal_line', 'two_minute', name='downdistancebucket'), nullable=False),
    sa.Column('frequency_note', sa.String(length=500), nullable=True),
    sa.Column('source_clip_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['scout_card_id'], ['scout_cards.id'], ),
    sa.ForeignKeyConstraint(['source_clip_id'], ['video_clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_periods',
    sa.Column('practice_script_id', sa.Uuid(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('period_name', sa.String(length=100), nullable=False),
    sa.Column('tempo', sa.Enum('walkthrough', 'indy', 'group', 'team', 'live', name='tempo'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['practice_script_id'], ['practice_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sideline_sheet_entries',
    sa.Column('sideline_sheet_id', sa.Uuid(), nullable=False),
    sa.Column('play_id', sa.Uuid(), nullable=False),
    sa.Column('down_distance_bucket', sa.Enum('first_10', 'second_short', 'second_medium', 'second_long', 'third_short', 'third_medium', 'third_long', 'fourth_down', 'red_zone', 'goal_line', 'two_minute', name='downdistancebucket'), nullable=False),
    sa.Column('field_zone', sa.Enum('own_territory', 'midfield', 'opp_territory', 'red_zone', 'goal_line', name='fieldzone'), nullable=True),
    sa.Column('hash_position', sa.Enum('left', 'middle', 'right', 'any', name='hashposition'), nullable=True),
    sa.Column('priority_tag_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], ),
    sa.ForeignKeyConstraint(['priority_tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['sideline_sheet_id'], ['sideline_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_reps',
    sa.Column('script_period_id', sa.Uuid(), nullable=False),
    sa.Column('play_id', sa.Uuid(), nullable=False),
    sa.Column('personnel_group_id', sa.Uuid(), nullable=False),
    sa.Column('rep_order', sa.Integer(), nullable=False),
    sa.Column('down_distance_bucket', sa.Enum('first_10', 'second_short', 'second_medium', 'second_long', 'third_short', 'third_medium', 'third_long', 'fourth_down', 'red_zone', 'goal_line', 'two_minute', name='downdistancebucket'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_group_id'], ['personnel_groups.id'], ),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], ),
    sa.ForeignKeyConstraint(['script_period_id'], ['script_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script_reps')
    op.drop_table('sideline_sheet_entries')
    op.drop_table('script_periods')
    op.drop_table('scout_card_entries')
    op.drop_table('play_tags')
    op.drop_table('clip_tags')
    op.drop_table('clip_play_links')
    op.drop_table('clip_annotations')
    op.drop_table('video_clips')
    op.drop_table('practice_scripts')
    op.drop_table('plays')
    op.drop_table('device_ack_receipts')
    op.drop_table('weekly_tasks')
    op.drop_table('sideline_sheets')
    op.drop_table('scout_cards')
    op.drop_table('role_assignments')
    op.drop_table('push_records')
    op.drop_table('formations')
    op.drop_index(op.f('ix_staff_members_email'), table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_table('personnel_groups')
    op.drop_table('game_plans')
    op.drop_table('teams')
    op.drop_table('tags')
    op.drop_table('roles')
    # ### end Alembic commands ###
